admin_homepage:
    pattern:  /indexSUPAD
    defaults: { _controller: AdminBundle:User:index }
admin_graphe:
    path:     /chartLine/{id}
    defaults: { _controller: AdminBundle:User:chartLine }   
tech_findTUY:
    path:     /findTUY/{epaisseur}
    defaults: { _controller: AdminBundle:Tech:findTUY }    
admin_updateprofile:
    pattern:  /updateProfile
    defaults: { _controller: AdminBundle:User:update }   
admin_updateOtherUser:
    pattern:  /updOtherUser/{id}
    defaults: { _controller: AdminBundle:User:updateOther }    
admin_afficheprofile:
    pattern:  /displayProfile
    defaults: { _controller: AdminBundle:User:affiche }  
admin_supprimeruser:
    pattern:  /deleteUser/{id}
    defaults: { _controller: AdminBundle:User:delete }    
admin_listerUser:
    pattern:  /listerUsers
    defaults: { _controller: AdminBundle:User:lister }     
tech_calculTole:
    pattern:  /calculTole
    defaults: { _controller: AdminBundle:Tech:calculTole }    
tech_listerTUYAUTERIES:
    pattern:  /listerTUY
    defaults: { _controller: AdminBundle:Tech:listerTUY }
tech_listProjet:
    pattern:  /listProjet
    defaults: { _controller: AdminBundle:Tech:listerProjet }    
tech_addProjet:
    pattern:  /addProjet
    defaults: { _controller: AdminBundle:Tech:addProjet}  
tech_addClient:
    pattern:  /addClient
    defaults: { _controller: AdminBundle:Tech:addClient}     
tech_listClient:
    pattern:  /listClient
    defaults: { _controller: AdminBundle:Tech:listerClient } 
tech_addPlan:
    pattern:  /addPlan/{id}
    defaults: { _controller: AdminBundle:Tech:addPlan}    
tech_genererPDFTUYAUTERIES:
    pattern:  /genererPDFTube
    defaults: { _controller: AdminBundle:Tech:generatePdfTube }    
tech_listerCOUDE:
    pattern:  /listerCOUDE
    defaults: { _controller: AdminBundle:Tech:listerCOUDE } 
tech_listerREDUCTION:
    pattern:  /listerRED
    defaults: { _controller: AdminBundle:Tech:listerRED }  
tech_index:
    pattern:  /indexTech
    defaults: { _controller: AdminBundle:Tech:index }    
