admin_homepage:
    pattern:  /indexSUPAD
    defaults: { _controller: AdminBundle:User:index }
admin_graphe:
    path:     /chartLine/{id}
    defaults: { _controller: AdminBundle:User:chartLine } 
admin_gantt:
    path:     /chartGantt/{id}
    defaults: { _controller: AdminBundle:User:chartGantt }    
admin_grapheSuivie:
    path:     /suivieChart/{id}
    defaults: { _controller: AdminBundle:User:suivieChart }     
tech_findTUY:
    path:     /findTUY/{epaisseur}
    defaults: { _controller: AdminBundle:Tech:findTUY }    
admin_updateprofile:
    pattern:  /updateProfile
    defaults: { _controller: AdminBundle:User:update }   
admin_updateOtherUser:
    pattern:  /updOtherUser/{id}
    defaults: { _controller: AdminBundle:User:updateOther }    
admin_afficheprofile:
    pattern:  /displayProfile
    defaults: { _controller: AdminBundle:User:affiche }  
admin_supprimeruser:
    pattern:  /deleteUser/{id}
    defaults: { _controller: AdminBundle:User:delete }    
admin_listerUser:
    pattern:  /listerUsers
    defaults: { _controller: AdminBundle:User:lister }     
tech_calculTole:
    pattern:  /calculTole/{id}
    defaults: { _controller: AdminBundle:Tech:calculTole }    
tech_listerTole:
    pattern:  /listerTole/{id}
    defaults: { _controller: AdminBundle:Tech:listerTole}
tech_listProjet:
    pattern:  /listProjet
    defaults: { _controller: AdminBundle:Tech:listerProjet }    
tech_listAvancement:
    pattern:  /listAvancement
    defaults: { _controller: AdminBundle:Tech:listerAvancement }   
tech_listPlan:
    pattern:  /listPlan
    defaults: { _controller: AdminBundle:Tech:listerPlan }     
tech_addProjet:
    pattern:  /addProjet
    defaults: { _controller: AdminBundle:Tech:addProjet}  
tech_addClient:
    pattern:  /addClient
    defaults: { _controller: AdminBundle:Tech:addClient}     
tech_listClient:
    pattern:  /listClient
    defaults: { _controller: AdminBundle:Tech:listerClient } 
tech_listTole:
    pattern:  /listTole
    defaults: { _controller: AdminBundle:Tech:listTole }     
tech_addAvancement:
    pattern:  /addAvancement/{id}
    defaults: { _controller: AdminBundle:Tech:addAvancement}    
tech_addPlan:
    pattern:  /addGantt/{id}
    defaults: { _controller: AdminBundle:Tech:addGantt}    
tech_addPlanification:
    pattern:  /addPlanification/{id}
    defaults: { _controller: AdminBundle:Tech:addPlan }     
tech_addMAD:
    pattern:  /addMAD/{id}
    defaults: { _controller: AdminBundle:Tech:addMAD }     
tech_genererPDFTUYAUTERIES:
    pattern:  /genererPDFTube
    defaults: { _controller: AdminBundle:Tech:generatePdfTube }    
tech_index:
    pattern:  /indexTech
    defaults: { _controller: AdminBundle:Tech:index }  
tech_updTUY:
    pattern:  /updTUY/{id}
    defaults: { _controller: AdminBundle:Tech:updateTUY }    
tech_updCoude:
    pattern:  /updCoude/{id}
    defaults: { _controller: AdminBundle:Tech:updateCoude }    
tech_updReduction:
    pattern:  /updRed/{id}
    defaults: { _controller: AdminBundle:Tech:updateRed }  
log_index:
    pattern:  /indexLog
    defaults: { _controller: AdminBundle:Log:index }     
log_addStock:
    pattern:  /addStock
    defaults: { _controller: AdminBundle:Log:addStock }      
log_listStock:
    pattern:  /listStock
    defaults: { _controller: AdminBundle:Log:listStock } 