<?php

namespace Proxies\__CG__\BackOffice\AdminBundle\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class MAD extends \BackOffice\AdminBundle\Entity\MAD implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function getDesignation()
    {
        $this->__load();
        return parent::getDesignation();
    }

    public function getDate()
    {
        $this->__load();
        return parent::getDate();
    }

    public function getDnext()
    {
        $this->__load();
        return parent::getDnext();
    }

    public function getLongueur()
    {
        $this->__load();
        return parent::getLongueur();
    }

    public function getCoude()
    {
        $this->__load();
        return parent::getCoude();
    }

    public function getReduction()
    {
        $this->__load();
        return parent::getReduction();
    }

    public function getTe()
    {
        $this->__load();
        return parent::getTe();
    }

    public function getBrides()
    {
        $this->__load();
        return parent::getBrides();
    }

    public function getVannes()
    {
        $this->__load();
        return parent::getVannes();
    }

    public function getEpaisseur()
    {
        $this->__load();
        return parent::getEpaisseur();
    }

    public function getCouche1()
    {
        $this->__load();
        return parent::getCouche1();
    }

    public function getCouche2()
    {
        $this->__load();
        return parent::getCouche2();
    }

    public function getCouche3()
    {
        $this->__load();
        return parent::getCouche3();
    }

    public function getQuantite()
    {
        $this->__load();
        return parent::getQuantite();
    }

    public function setId($id)
    {
        $this->__load();
        return parent::setId($id);
    }

    public function setIdprojet(\BackOffice\AdminBundle\Entity\Projet $idprojet = NULL)
    {
        $this->__load();
        return parent::setIdprojet($idprojet);
    }

    public function getIdprojet()
    {
        $this->__load();
        return parent::getIdprojet();
    }

    public function setDesignation($designation)
    {
        $this->__load();
        return parent::setDesignation($designation);
    }

    public function setDate(\DateTime $date)
    {
        $this->__load();
        return parent::setDate($date);
    }

    public function setDnext($dnext)
    {
        $this->__load();
        return parent::setDnext($dnext);
    }

    public function setLongueur($longueur)
    {
        $this->__load();
        return parent::setLongueur($longueur);
    }

    public function setCoude($coude)
    {
        $this->__load();
        return parent::setCoude($coude);
    }

    public function setReduction($reduction)
    {
        $this->__load();
        return parent::setReduction($reduction);
    }

    public function setTe($te)
    {
        $this->__load();
        return parent::setTe($te);
    }

    public function setBrides($brides)
    {
        $this->__load();
        return parent::setBrides($brides);
    }

    public function setVannes($vannes)
    {
        $this->__load();
        return parent::setVannes($vannes);
    }

    public function setEpaisseur($epaisseur)
    {
        $this->__load();
        return parent::setEpaisseur($epaisseur);
    }

    public function setCouche1($couche1)
    {
        $this->__load();
        return parent::setCouche1($couche1);
    }

    public function setCouche2($couche2)
    {
        $this->__load();
        return parent::setCouche2($couche2);
    }

    public function setCouche3($couche3)
    {
        $this->__load();
        return parent::setCouche3($couche3);
    }

    public function setQuantite($quantite)
    {
        $this->__load();
        return parent::setQuantite($quantite);
    }

    public function getTuyauterie()
    {
        $this->__load();
        return parent::getTuyauterie();
    }

    public function getCouche4()
    {
        $this->__load();
        return parent::getCouche4();
    }

    public function getCouche5()
    {
        $this->__load();
        return parent::getCouche5();
    }

    public function setTuyauterie($tuyauterie)
    {
        $this->__load();
        return parent::setTuyauterie($tuyauterie);
    }

    public function setCouche4($couche4)
    {
        $this->__load();
        return parent::setCouche4($couche4);
    }

    public function setCouche5($couche5)
    {
        $this->__load();
        return parent::setCouche5($couche5);
    }

    public function getSurface()
    {
        $this->__load();
        return parent::getSurface();
    }

    public function setSurface($surface)
    {
        $this->__load();
        return parent::setSurface($surface);
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'designation', 'date', 'dnext', 'longueur', 'coude', 'tuyauterie', 'surface', 'reduction', 'te', 'brides', 'vannes', 'epaisseur', 'couche1', 'couche2', 'couche3', 'couche4', 'couche5', 'quantite', 'idprojet');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}