<?php

namespace Proxies\__CG__\BackOffice\AdminBundle\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Projet extends \BackOffice\AdminBundle\Entity\Projet implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function getNature()
    {
        $this->__load();
        return parent::getNature();
    }

    public function getLieu()
    {
        $this->__load();
        return parent::getLieu();
    }

    public function getBesoinEchaffaudage()
    {
        $this->__load();
        return parent::getBesoinEchaffaudage();
    }

    public function getBesoinHebergement()
    {
        $this->__load();
        return parent::getBesoinHebergement();
    }

    public function getNbBesoinHebergement()
    {
        $this->__load();
        return parent::getNbBesoinHebergement();
    }

    public function getNbJourPrefa()
    {
        $this->__load();
        return parent::getNbJourPrefa();
    }

    public function getNbJourMonta()
    {
        $this->__load();
        return parent::getNbJourMonta();
    }

    public function getDatePrefa()
    {
        $this->__load();
        return parent::getDatePrefa();
    }

    public function getDateMonta()
    {
        $this->__load();
        return parent::getDateMonta();
    }

    public function getNbPersPrefa()
    {
        $this->__load();
        return parent::getNbPersPrefa();
    }

    public function getNbPersMonta()
    {
        $this->__load();
        return parent::getNbPersMonta();
    }

    public function getMargebenef()
    {
        $this->__load();
        return parent::getMargebenef();
    }

    public function getRemise()
    {
        $this->__load();
        return parent::getRemise();
    }

    public function getBesoinMaterielRoulant()
    {
        $this->__load();
        return parent::getBesoinMaterielRoulant();
    }

    public function getBesoinMatierePremiere()
    {
        $this->__load();
        return parent::getBesoinMatierePremiere();
    }

    public function getCoutEPI()
    {
        $this->__load();
        return parent::getCoutEPI();
    }

    public function getQuantiteEPI()
    {
        $this->__load();
        return parent::getQuantiteEPI();
    }

    public function getContact()
    {
        $this->__load();
        return parent::getContact();
    }

    public function getEtat()
    {
        $this->__load();
        return parent::getEtat();
    }

    public function getDateMiseDispo()
    {
        $this->__load();
        return parent::getDateMiseDispo();
    }

    public function getPrixUnitaire()
    {
        $this->__load();
        return parent::getPrixUnitaire();
    }

    public function getPrixTotal()
    {
        $this->__load();
        return parent::getPrixTotal();
    }

    public function getCharges()
    {
        $this->__load();
        return parent::getCharges();
    }

    public function setId($id)
    {
        $this->__load();
        return parent::setId($id);
    }

    public function setNature($nature)
    {
        $this->__load();
        return parent::setNature($nature);
    }

    public function setLieu($lieu)
    {
        $this->__load();
        return parent::setLieu($lieu);
    }

    public function setBesoinEchaffaudage($besoinEchaffaudage)
    {
        $this->__load();
        return parent::setBesoinEchaffaudage($besoinEchaffaudage);
    }

    public function setBesoinHebergement($besoinHebergement)
    {
        $this->__load();
        return parent::setBesoinHebergement($besoinHebergement);
    }

    public function setNbBesoinHebergement($nbBesoinHebergement)
    {
        $this->__load();
        return parent::setNbBesoinHebergement($nbBesoinHebergement);
    }

    public function setNbJourPrefa($nbJourPrefa)
    {
        $this->__load();
        return parent::setNbJourPrefa($nbJourPrefa);
    }

    public function setNbJourMonta($nbJourMonta)
    {
        $this->__load();
        return parent::setNbJourMonta($nbJourMonta);
    }

    public function setDatePrefa(\DateTime $datePrefa)
    {
        $this->__load();
        return parent::setDatePrefa($datePrefa);
    }

    public function setDateMonta(\DateTime $dateMonta)
    {
        $this->__load();
        return parent::setDateMonta($dateMonta);
    }

    public function setNbPersPrefa($nbPersPrefa)
    {
        $this->__load();
        return parent::setNbPersPrefa($nbPersPrefa);
    }

    public function setNbPersMonta($nbPersMonta)
    {
        $this->__load();
        return parent::setNbPersMonta($nbPersMonta);
    }

    public function setMargebenef($margebenef)
    {
        $this->__load();
        return parent::setMargebenef($margebenef);
    }

    public function setRemise($Remise)
    {
        $this->__load();
        return parent::setRemise($Remise);
    }

    public function setBesoinMaterielRoulant($besoinMaterielRoulant)
    {
        $this->__load();
        return parent::setBesoinMaterielRoulant($besoinMaterielRoulant);
    }

    public function setBesoinMatierePremiere($besoinMatierePremiere)
    {
        $this->__load();
        return parent::setBesoinMatierePremiere($besoinMatierePremiere);
    }

    public function setCoutEPI($coutEPI)
    {
        $this->__load();
        return parent::setCoutEPI($coutEPI);
    }

    public function setQuantiteEPI($quantiteEPI)
    {
        $this->__load();
        return parent::setQuantiteEPI($quantiteEPI);
    }

    public function setContact($contact)
    {
        $this->__load();
        return parent::setContact($contact);
    }

    public function setEtat($etat)
    {
        $this->__load();
        return parent::setEtat($etat);
    }

    public function setDateMiseDispo(\DateTime $dateMiseDispo)
    {
        $this->__load();
        return parent::setDateMiseDispo($dateMiseDispo);
    }

    public function setPrixUnitaire($prixUnitaire)
    {
        $this->__load();
        return parent::setPrixUnitaire($prixUnitaire);
    }

    public function setPrixTotal($prixTotal)
    {
        $this->__load();
        return parent::setPrixTotal($prixTotal);
    }

    public function setCharges($charges)
    {
        $this->__load();
        return parent::setCharges($charges);
    }

    public function getQuantite()
    {
        $this->__load();
        return parent::getQuantite();
    }

    public function setQuantite($quantite)
    {
        $this->__load();
        return parent::setQuantite($quantite);
    }

    public function setIdclient(\BackOffice\AdminBundle\Entity\Client $idClient = NULL)
    {
        $this->__load();
        return parent::setIdclient($idClient);
    }

    public function getIdclient()
    {
        $this->__load();
        return parent::getIdclient();
    }

    public function __toString()
    {
        $this->__load();
        return parent::__toString();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'nature', 'lieu', 'quantite', 'besoinEchaffaudage', 'besoinHebergement', 'nbBesoinHebergement', 'nbJourPrefa', 'nbJourMonta', 'datePrefa', 'dateMonta', 'nbPersPrefa', 'nbPersMonta', 'margebenef', 'Remise', 'besoinMaterielRoulant', 'besoinMatierePremiere', 'coutEPI', 'quantiteEPI', 'contact', 'etat', 'dateMiseDispo', 'prixUnitaire', 'prixTotal', 'charges', 'idClient');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}