<?php

namespace Proxies\__CG__\BackOffice\AdminBundle\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Client extends \BackOffice\AdminBundle\Entity\Client implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function getSociete()
    {
        $this->__load();
        return parent::getSociete();
    }

    public function getSecteurActivite()
    {
        $this->__load();
        return parent::getSecteurActivite();
    }

    public function getTelephone()
    {
        $this->__load();
        return parent::getTelephone();
    }

    public function getTelecopie()
    {
        $this->__load();
        return parent::getTelecopie();
    }

    public function getTitreContact()
    {
        $this->__load();
        return parent::getTitreContact();
    }

    public function getContact()
    {
        $this->__load();
        return parent::getContact();
    }

    public function setId($id)
    {
        $this->__load();
        return parent::setId($id);
    }

    public function setSociete($societe)
    {
        $this->__load();
        return parent::setSociete($societe);
    }

    public function setSecteurActivite($secteurActivite)
    {
        $this->__load();
        return parent::setSecteurActivite($secteurActivite);
    }

    public function setTelephone($telephone)
    {
        $this->__load();
        return parent::setTelephone($telephone);
    }

    public function setTelecopie($telecopie)
    {
        $this->__load();
        return parent::setTelecopie($telecopie);
    }

    public function setTitreContact($titreContact)
    {
        $this->__load();
        return parent::setTitreContact($titreContact);
    }

    public function setContact($contact)
    {
        $this->__load();
        return parent::setContact($contact);
    }

    public function getMatricule()
    {
        $this->__load();
        return parent::getMatricule();
    }

    public function getImage()
    {
        $this->__load();
        return parent::getImage();
    }

    public function setMatricule($matricule)
    {
        $this->__load();
        return parent::setMatricule($matricule);
    }

    public function setImage($image)
    {
        $this->__load();
        return parent::setImage($image);
    }

    public function getMail()
    {
        $this->__load();
        return parent::getMail();
    }

    public function setMail($mail)
    {
        $this->__load();
        return parent::setMail($mail);
    }

    public function __toString()
    {
        $this->__load();
        return parent::__toString();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'societe', 'secteurActivite', 'matricule', 'telephone', 'telecopie', 'titreContact', 'contact', 'image', 'mail');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}